### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bsthorpe** [alanjfs/sequentity#13]
Hello,

Would you consider licensing the software under a standard bsd-2 license?  I wouldn't be permitted to provide a copy of the software or the software product being developed for a customer.

Thanks.

**Comment by alanjfs** [comment]
Sorry, the wheels are already in motion. I'd suggest enquiring with your customer whether this project is worth the cost of one copy of their software.

- [Licence, for reference](https://github.com/alanjfs/sequentity/blob/08b041798fa2680897a34e894eda1c187f1d02db/Sequentity.h#L1424)

**Comment by bsthorpe** [comment]
Thanks for the reply. I figured I'd ask.  

It's unfortunately not a commercial product, and for a government customer... makes everything complicated.  Ironically, the software is free to use for government purposes, so a copy isn't worth much, and they aren't in the business of selling things...The cost of getting approval to release it externally... the bureaucracy alone...

I was hoping to use it as a way to visualize and manipulate event timelines within simulation software.  If you are interested in discussing further please send me an e-mail.

**Comment by alanjfs** [comment]
E-mail sent, let's continue the conversation there.
