### ISSUE TITLE
Safe guards for operator overloading?

### ISSUE THREAD

**Issue by melMass** [alanjfs/sequentity#14]
Hi,

This might be due to the limits of what I know so I'm not sure if it's an issue or a support request :)

I'm using ImGui's math overloads by using the define `IMGUI_DEFINE_MATH_OPERATORS` 

https://github.com/ocornut/imgui/blob/d6a5cc7934b4f4f9d5effffc4f1acee151247f51/imgui_internal.h#L4-L7

doing that conflicts with yours, and I have no idea how to overcome that... I'm using those in a bunch of places in my own libraries.

Is there a way to make the overloads available only inside a namespace for instance or a way to avoid clashes?

Thanks

**Comment by alanjfs** [comment]
Eeek, good question.

You are referring to these?

https://github.com/alanjfs/sequentity/blob/08b041798fa2680897a34e894eda1c187f1d02db/Sequentity.h#L267-L302

It *would* be great limiting those to happening within Sequentity. If you manage to do that, I'd welcome a PR.

**Comment by melMass** [comment]
Yes exactly!
I'm on it today, I'll see if I can find a solution.

**Comment by melMass** [comment]
Alright, it seems that the ones defined by ImGui are defined in the global namespace, creating ambiguity.
I was sure to have already tested it but apparently not. One should not actually use `IMGUI_DEFINE_MATH_OPERATORS` for this reason, and your approach is actually portable (I did the same and defined those operators inline in a namespace).

Thanks, closing!
