### ISSUE TITLE
Newbie question... How to generate the VS project...?

### ISSUE THREAD

**Issue by moebiussurfing** [alanjfs/sequentity#15]
Hey @alanjfs , thanks for sharing this. It looks really cool.

Sorry for this silly question, 
Just learning to compile the project.
But could you write some lines about generating the projects?

What I am doing wrong?

- Way 1: 
I downloaded Ninja and added it to the system path environment 
(Because it was mentioned into Example/CMakeSettings.json)

From the sequentity-master/example folder I run cmake -G Ninja, and I am getting this errors:

`PS F:\openFrameworks\addons\ofxSurfingImGui\examples\5_Sequentity\MISC\sequentity-master\sequentity-master\Example> cmake -G Ninja`

```.bash
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "F:/openFrameworks/addons/ofxSurfingImGui/examples/5_Sequentity/MISC/sequentity-master/sequentity-master/Example/CMakeFiles/CMakeOutput.log".
See also "F:/openFrameworks/addons/ofxSurfingImGui/examples/5_Sequentity/MISC/sequentity-master/sequentity-master/Example/CMakeFiles/CMakeError.log".
PS F:\openFrameworks\addons\ofxSurfingImGui\examples\5_Sequentity\MISC\sequentity-master\sequentity-master\Example>
```

- Way 2:
When using the Gui version of make I have come further and created the VS2017/VS2019 projects, 
but I am having errors when compiling:

![seq1](https://user-images.githubusercontent.com/2106149/123528503-00c56980-d6be-11eb-9b1d-d3854b9f5963.PNG)

![seq2](https://user-images.githubusercontent.com/2106149/123528505-0458f080-d6be-11eb-9901-4a4322e78277.PNG)

![seq3](https://user-images.githubusercontent.com/2106149/123528508-091da480-d6be-11eb-91a4-831cfefd0aaf.PNG)

**Comment by alanjfs** [comment]
Hi @moebiussurfing, sorry for the late reply.

The example ships with pre-compiled binaries, but they are for Visual Studio 2015. Try that, and it should work.

```bash
cd sequentity
mkdir build
cd build
vcvarsall.bat
cmake .. -GNinja
ninja
```

Alternatively:

```bash
cmake .. -G "Visual Studio 14 2015" -T v140
```

Alternatively alternatively, grab the original projects like Magnum and build them all under the same roof. The example is only an example, Sequentity does not depend on it. If you just want to try it, there's the pre-compiled exe you can download as well.

**Comment by alanjfs** [comment]
Actually come to think of it, the example doesn't need building, you can open it as-is in Visual Studio 2017/2019 as a CMakeProject. You'll just need to have the VS2015 runtime (called v140) installed, and all should be well.

**Comment by moebiussurfing** [comment]
Thanks @alanjfs for your reply. 
I'll check what you say. I am installing that VS2015 stuff and I'll report here.

I already tried the exe binary and I liked it. 

What I want to do is a kind of "isolate" the ImGui part to build inside my openFrameworks projects. 
I usually use ImGui stuff inside oF perfectly. (I "ported" ImSequencer, ImGuizmo, DearWidgets...etc)

But I see that you use entt and never used Magnum, neither. So I need to remove all the window/GL stuff and so on.
Not sure how much dependent could be sequentity to all this... Do you think this could be so hard?
I will report back about my progress.

**Comment by moebiussurfing** [comment]
I just made it work in openFrameworks, nightly builds that enables C++17.
just in case some one interested:
https://github.com/moebiussurfing/ofxSurfingImGuiExtra/tree/master/5_Timeline/5_3_Sequentity3
